name: shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/logo.png
    # TODO: Add slanted menu asset (104)
    - assets/0-0.png
    - assets/1-0.png
    - assets/2-0.png
    - assets/3-0.png
    - assets/4-0.png
    - assets/5-0.png
    - assets/6-0.png
    - assets/7-0.png
    - assets/8-0.png
    - assets/9-0.png
    - assets/10-0.png
    - assets/11-0.png
    - assets/12-0.png
    - assets/13-0.png
    - assets/14-0.png
    - assets/15-0.png
    - assets/16-0.png
    - assets/17-0.png
    - assets/18-0.png
    - assets/19-0.png
    - assets/20-0.png
    - assets/21-0.png
    - assets/22-0.png
    - assets/23-0.png
    - assets/24-0.png
    - assets/25-0.png
    - assets/26-0.png
    - assets/27-0.png
    - assets/28-0.png
    - assets/29-0.png
    - assets/30-0.png
    - assets/31-0.png
    - assets/32-0.png
    - assets/33-0.png
    - assets/34-0.png
    - assets/35-0.png
    - assets/36-0.png
    - assets/37-0.png
    - assets/38-0.png
    - assets/39-0.png
    - assets/40-0.png
    - assets/41-0.png
    - assets/42-0.png
    - assets/43-0.png
    - assets/44-0.png
    - assets/45-0.png
    - assets/46-0.png
